library(tidyverse)
library(ggfortify)
library(factoextra)
library(ggExtra)
library(uwot)
library(Rtsne)
library(ggpubr)
library(effsize)

theme_set(theme_classic())

# Importing the data and factoring it, so the groups are set correctly for the effect size analysis later
tumor_df <- read.csv("BreastCancerWisconsin.csv") %>%
  group_by(Diagnosis)
tumor_df$Diagnosis <- factor(tumor_df$Diagnosis, levels = c("M", "B"))

# Generation of the pca data
tumor.pca <- prcomp(tumor_df[, c(3:12)],
                    center = TRUE,
                    scale. = TRUE)

# Creating an object with the pca plot
tumor.pca.plot <- autoplot(tumor.pca, data = tumor_df, color = "Diagnosis", alpha = 0.7, size = 1.5) +
  scale_color_manual(values = c("#0073C2FF", "#EFC000FF"), labels = c("B" = "Benign", "M" = "Malignant")) +
  scale_fill_manual(values = c("#0073C2FF", "#EFC000FF")) +
  coord_equal() +
  theme(
    panel.grid = element_blank(),
    legend.title = element_text(hjust = 0.5)
  )

# Plotting the PCA plot, with the density plots overlayed
ggMarginal(tumor.pca.plot, margins = "x", type = "density", groupColour = TRUE, groupFill = TRUE, alpha = 0.3)

# Contributions of each PC - as visual plots
fviz_contrib(tumor.pca, choice = "var", axes = 1)
fviz_contrib(tumor.pca, choice = "var", axes = 2)

# Contributions of each PC - as numeric vectors
contributions <- get_pca_var(tumor.pca)$contrib
pc1_contributions <- sort(contributions[,"Dim.1"], decreasing = TRUE)
pc2_contributions <- sort(contributions[,"Dim.2"], decreasing = TRUE)

print(pc1_contributions)

### This was code that I (Ryan) used to experiment with the other dimension reduction techniques ###
### The actual code for the plots generated is not from the following block ###
tumor.uwot <- umap(as.matrix(tumor_df[, c(3:12)]), n_neighbors = 15, min_dist = 0.1, scale = TRUE)
tumor.umap.df <- as.data.frame(tumor.uwot) %>%
  rename(UMAP1 = V1, UMAP2 = V2)

tumor.umap.df$Diagnosis <- tumor_df$Diagnosis

ggplot(tumor.umap.df, aes(x = UMAP1, y = UMAP2, color = Diagnosis)) +
  geom_point() +
  scale_color_manual(values = c("#0073C2FF", "#EFC000FF"), labels = c("B" = "Benign", "M" = "Malignant"))


tumor_scaled <- scale(tumor_df[, c(3:12)])
tumor_matrix <- as.matrix(tumor_scaled)  
set.seed(9000)
tsne_results <- Rtsne(tumor_matrix, dims = 2, perplexity = 50, verbose = TRUE, max_iter = 1000)

tsne_df <- data.frame (
  X = tsne_results$Y[, 1],
  Y = tsne_results$Y[, 2]
)

tsne_df$Diagnosis <- tumor_df$Diagnosis

ggplot(tsne_df, aes(x = X, y = Y, color = Diagnosis)) +
  geom_point() +
  scale_color_manual(values = c("#0073C2FF", "#EFC000FF"), labels = c("B" = "Benign", "M" = "Malignant"))
###################################################################################################

# Testing to see if the distributions for the radius are significantly different with a wilcoxon test
wilcox.test(radius ~ Diagnosis, data = tumor_df)

# Plotting violin plot with radius distributions for benign and malignant, along with the p-value for the
# Wilcoxon test displayed over it
ggplot(tumor_df, aes(x = Diagnosis, y = concave_points, fill = Diagnosis)) +
  geom_violin(alpha = 0.5) +
  geom_boxplot(width = 0.1, color = "black", outlier.shape = NA, fill = "white", alpha = 0.4) +
  stat_compare_means(comparisons = list(c("B", "M")),
                     label = "p.value",
                     method = "wilcox.test") +
  labs(y = "Concave Points") +
  scale_fill_manual(values = c("#0073C2FF", "#EFC000FF"), labels = c("B" = "Benign", "M" = "Malignant")) +
  theme(legend.position = "none")

#######################################################################################################

# Creation of function to find relevant metrics from cohen's d output
find_cohen <- function(dimension) {
  form <- as.formula(paste0(dimension, " ~ Diagnosis"))
  result <- cohen.d(form, data = tumor_df)
  c(effect_size = result$estimate,
    lower_bound = unname(result$conf.int[1]),
    upper_bound = unname(result$conf.int[2]))
  
}
row_names = c("Radius", "Area", "Texture", "Concave Points", "Concavity", "Perimeter", "Smoothness",
                 "Symmetry", "Compactness", "Fractal Dimension")
variable_names = c("radius", "area","texture", "concave_points",
                  "concavity", "perimeter", "smoothness",
                  "symmetry", "compactness", "fractal_dimension")

effect_sizes <- data.frame(
  dimension_labels = row_names,
  t(sapply(variable_names, find_cohen)),
  row.names = NULL
)

# Creating the effect size plot using the information generated by the cohen's d function
ggplot(effect_sizes, aes(x = effect_size, y = reorder(dimension_labels, effect_size))) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 0.6) + 
  geom_vline(aes(xintercept = 0.2, color = "d = 0.2 Small"), linetype = "twodash", linewidth = 0.6) + 
  geom_vline(aes(xintercept = 0.5, color = "d = 0.5 Moderate"), linetype = "twodash", linewidth = 0.6) + 
  geom_vline(aes(xintercept = 0.8, color = "d = 0.8 Large"), linetype = "twodash", linewidth = 0.6) + 
  geom_errorbarh(aes(xmin = lower_bound, xmax = upper_bound), width = 0.2, color = "#003366", linewidth = 1) +
  geom_point(size = 2, color = "#4682B4") +
  labs(x = "Cohen's d (95% Confidence Interval)", y = "", title = "Cohen's d Effect Sizes for Tumor Dimensions in Benign vs. Malignant Tumors") +
  theme_minimal() +
  theme(text = element_text(size = 12),
        panel.grid.minor = element_blank()) +
  scale_color_manual(name = "Effect Size Cutoffs",
  values = c("d = 0.2 Small" = "#56B4E9",
             "d = 0.5 Moderate" ="#E69F00",
             "d = 0.8 Large" = "#CC79A7"))
